### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by patrickherring-TRI** [TRI-AMDD/beep#106]
As a developer

I need to know what columns are necessary for subsequent processing steps, especially structuring

so that I can convert and rename the right columns and determine if I am missing any requirements

Acceptance Criteria:

List of columns needed for structuring, their contents, units, data types, and standardized name

**Comment by patrickherring-TRI** [comment]
beep/conversion_schemas has a lot of the columns necessary to run the structuring so

**Comment by ardunn** [comment]
@patrickherring-TRI by "standardized name" you mean the required name (`has_special`) and not the internal mapping (`_has_special`), correct?

**Comment by patrickherring-TRI** [comment]
@ardunn Yes, the required name should be something like `cycle_index`. Most of the internal mapping ones are not used in the structuring process.
A: For this we only care about being able to create a ProcessedCyclerRun object 
Yes, I think that `data_point` is not actually required for any of the processing. Likewise, I think that `step_time` is not actually used by any of the functions

**Comment by ardunn** [comment]
Ok I will systematically try removing columns from the test case and see when ProcessedCyclerRun fails. I'll list all the columns for completeness and mark the required ones as "required"
