### ISSUE TITLE
[mat-2116] Rework CLI using Click, remove JSON requirements for use

### ISSUE THREAD

**Issue by ardunn** [TRI-AMDD/beep#107]
As a new user, the usage of console scripts is made more difficult by:

1. using the console scripts requires back+forth between the readme and the cmd line, e.g., console scripts do not follow a standard "--help" interface:

cmd:
```
$: collate --help
```

out (no cli help shown):
```
0it [00:00, ?it/s]
{"fid": [], "protocol": [], "channel_no": [], "date": [], "strname": [], "filename": [], "file_list": []}(beepenv) 
```
2. Current commands require json strings as input rather than canonical cli arguments

3. The default command names also may interfere with other common console scripts (anything named `validate` in the user's path, for example)

4. current command line interface relies on setting various env variables and assuming an underlying directory structure - may be improved if console scripts also had a `--processing-path` or similar option.

---

A framework like [Click](https://click.palletsprojects.com/en/7.x/) can help simplify and improve the scripts, for example:

```
$ beep collate --help
Usage: beep collate [OPTIONS]

  Beep collate documentation blah blah blah...

Options:
  --filename PATH          Path to the file
  --output directory PATH  Path to the output/processing directory
```

I've used click before and it is a great framework for engineering cli scripts

**Comment by ardunn** [comment]
please close if not useful or wrong place

**Comment by patrickherring-TRI** [comment]
Totally agree, it would be nice to clean up the cli interface. Thanks for the suggestion!
The json format is a hold-over from our previous event based workflow so I think it's probably time to update them.
@moorepatrick Now that we are using Argo for workflow management would it be hard to change the commands for the container so that more cli compatible commands are used?

**Comment by patrickherring-TRI** [comment]
@ardunn Click sounds like a pretty good option. We have used docopt in the past, but that tends to be a little clunky and click seems to have a simple interface that does not clutter up the code (or documentation).

**Comment by moorepatrick** [comment]
The workflows should not be impacted by this too much. They have actually mostly moved away from any lists in the input so having arguments instead would make things look a lot cleaner.

One thing to consider before we go too far down the path of a single CLI tool is how we plan to allow custom processing tasks.

**Comment by ardunn** [comment]
@moorepatrick are there clear custom processing cases where a single CLI tool would not work? It may help to enumerate some now so if we transfer over to Click we can write the code with those in mind.

**Comment by moorepatrick** [comment]
@ardunn We have not identified any specific use cases, yet but it probably deserves a full discussion.

**Comment by ardunn** [comment]
from #120

## Problem

Not sure if this is an actual problem, since users of beep may just have one set of files they are working with, but when you are working with multiple input files, keeping track of what is going on with each file with the CLI + data-share directory is complicated...

## Solution
Simply input and output files in the working directory according to whatever names the user wants (or sensible defaults in the cwd if no args passed), should be possible wth #107

**Comment by ardunn** [comment]
https://docs.google.com/document/d/17MdS8JfxcFBeJg6OjmWviCjqGsMs7uYXHP1KObNaCsA/edit?usp=sharing
