### ISSUE TITLE
[Bug] principle_components module seems to never be used anywhere

### ISSUE THREAD

**Issue by ardunn** [TRI-AMDD/beep#124]
Perhaps this is another "specific to AWS" feature, in which case it would fall under #121

**Comment by ardunn** [comment]
@chirranjeevigopal-TRI @patrickherring-TRI is this module going to be used down the line?

**Comment by patrickherring-TRI** [comment]
@ardunn Yeah, we still think we will use it, but it will need to be integrated into the validation module in order to function correctly.

**Comment by chirranjeevigopal-TRI** [comment]
Yeah, PCA or some unsupervised method to pick out anomalies will become part of the validation in the future. We have not gotten around to it yet, but will definitely do so.
