### ISSUE TITLE
Possibly incorrect cell selection to match Nature Energy paper

### ISSUE THREAD

**Issue by jkoeller** [TRI-AMDD/beep#148]
👋 Hi! 

The `discards` cells listed here: https://github.com/TRI-AMDD/beep/blob/cca82e75a241f4545cc4f0fa86c606f1d057690a/scripts/batch_generate_structure_feature.py#L31 look like they were designed to match the cells listed here: https://github.com/rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation/blob/master/Load%20Data.ipynb. However, I don't think the cell numbers in the second link refer to channel numbers, as their use in the first link implies. The notes for each of the batches here https://data.matr.io/1/projects/5c48dd2bc625d700019f3204 describe a different set of cells being left out of the Nature Energy paper due to various issues. Table 9 in the supplementary info of the paper has barcodes consistent with the cells referenced in the third link, and is inconsistent with the cells "discarded" in the first link.

Please do let me know if I am misunderstanding something. I'm trying to get the "cleanest" dataset possible from the data collected in the Nature Energy paper. My current understanding is that this requires removing the cells listed in the third link above.

**Comment by patrickherring-TRI** [comment]
@jkoeller The cells listed on the data.matr.io/1 page should be regarded as the most canonical. As always, discarding outliers is more of an art than a science and different people have made different choices over time 🤷

**Comment by jkoeller** [comment]
Understood. Just wanted to point out this discrepancy to prevent future confusion!

**Comment by patrickherring-TRI** [comment]
Yeah, thanks for pointing that out. We can definitely change the beep discards to match the Nature Energy paper!
