### ISSUE TITLE
Structuring with large (>~180MB) Arbin CSV files hangs

### ISSUE THREAD

**Issue by jkoeller** [TRI-AMDD/beep#149]
There are around 16 csv files in the Nature Energy dataset which "validate" but cannot be "structured". The structuring command simply hangs at this step forever: 

![image](https://user-images.githubusercontent.com/2541554/98429989-2cc4a980-205f-11eb-8ef4-7086d7e5543b.png)

This is the code I am running, which works fine on all of the other files from the dataset: 

```
for file in file_list:
    print(file)
    mode = 'events_off'
    mapped  =  {
                "mode": mode,  # mode run|test|events_off
                "file_list": [file],  # list of file paths ['path/test1.csv', 'path/test2.csv']
                'run_list': [0]  # list of run_ids [0, 1]
                }
    mapped = json.dumps(mapped)

    # Validation
    validated = validate.validate_file_list_from_json(mapped)
    validated_output = json.loads(validated)
    validated_output['mode'] = mode  # mode run|test|events_off
    validated_output['run_list'] = list(range(len(validated_output['file_list'])))
    validated = json.dumps(validated_output)
    print('Validated:', validated)

    # Data structuring
    structured = structure.process_file_list_from_json(validated)
    structured_output = json.loads(structured)
    structured_output['mode'] = mode  # mode run|test|events_off
    structured_output['run_list'] = list(range(len(structured_output['file_list'])))
    structured = json.dumps(structured_output)
    print('Structured:', structured)
```

The files which have this problem are these:
![image](https://user-images.githubusercontent.com/2541554/98430025-70b7ae80-205f-11eb-81d4-e357b204a553.png)

It appears to only be the large files that are affected.

I may debug this further next week, but wanted to post it here to see if this is a known issue or if there is a simple fix I am overlooking. Thanks!

**Comment by patrickherring-TRI** [comment]
@jkoeller Hi, thanks for reporting this!
I tried out a couple of the files that you showed above and it looks like the structuring succeeds although it does take longer than I would expect. I will look into what process is taking up so much CPU time.

One thing that might be happening is an out of memory issue causing your kernel to crash. Generally, the structuring process takes ~5x the memory footprint of the raw file (pandas being what it is). So a 300MB file might require ~2GB of RAM to complete successfully.

After structuring, the structured file has a considerably smaller memory footprint and is much easier to work with.

**Comment by ardunn** [comment]
@patrickherring-TRI some of these memory issues might be fixed by using in place operations for the dataframes. For example, in RawCyclerRun.get_interpolated_data() the dataframe seems to be copied in memory several times

**Comment by jkoeller** [comment]
I just let it run for a while, and you're right @patrickherring-TRI it does eventually process after not appearing to make any progress for a while. I was able to process all of the files with an average time of 15 min / file. Interestingly, the RAM utilization (at least in the beginning, while appearing not to progress) is quite low. Not sure what the slowdown is. The files of size < 160 MB process in around 1 min or so. 

Thanks for looking into this!

**Comment by patrickherring-TRI** [comment]
This delay appears to be due to the initial data loading process which for large files can be resource intensive. New pandas functions might be able to speed up this process, but a better solution will be the larger refactor of the structuring module. Closing this issue for now since it is system dependent.
