### ISSUE TITLE
[Bug] Pandas Indexing Deprecated

### ISSUE THREAD

**Issue by MattMazz25** [TRI-AMDD/beep#174]
There seems to be an issue with the from_run method in the DeltaQFastCharge class in the featurize.py file. I ran into this error when taking the 2017-05-12_5_4C-40per_3_6C_CH18 data and editing it into my own file called “b1_CH18.csv” and running through the code below.
 
![image](https://user-images.githubusercontent.com/43766428/109347893-abb93a00-7828-11eb-8190-01577d8b1114.png)

![image](https://user-images.githubusercontent.com/43766428/109347946-bd9add00-7828-11eb-817d-cae9b965d66f.png)

![image](https://user-images.githubusercontent.com/43766428/109347967-c4295480-7828-11eb-828d-5e6375d92340.png)

I believe that there is more likely than not an issue with my csv file, however it does point out an error when handling a newer version of pandas. I am currently running pandas version 1.1.5. It appears that some the cycle indices get dropped when I call dropna(), but when there are missing cycles, it returns an error about not being able to index in to the dataframe with missing cycles. Looks like the current method being used is deprecated and is replaced by using .reindex() or index.intersection().

`https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-deprecate-loc-reindex-listlike`

Just wanted to let you all know of this.

Thanks!

**Comment by patrickherring-TRI** [comment]
Hi Matt,
Thanks for writing this up. As you say there appears to be some pandas usage that is out of date and I have created a PR that updates the usage to reflect the current pandas indexing calls. I do think that the root problem in the code snippet you showed is the `.dropna()` line which is likely removing a significant fraction of the data in the file (possibly all of it). A more careful filtering might allow you to drop the values that are causing issues while retaining the necessary data to run the feature generation.

Thanks!
Patrick
