### ISSUE TITLE
[Feature Request] Optional loading of `raw_data` attribute

### ISSUE THREAD

**Issue by patrickherring-TRI** [TRI-AMDD/beep#239]
**Problem statement**
Loading of the structured files used to be relative fast since the files contained only the interpolated dataframes and these were much smaller. Having the raw data available is very convenient but slows down the loading time and dramatically increases the amount of memory required.

**Solution suggestion**
Making the loading the of the raw data optional should solve the problem, so that unless a flag was set, the attribute would remain empty (using the `auto_load_processed` method). However, it's also desirable to make the to/from file methods simple and transparent so if a lot of additional complexity is required this might not be the best solution.

**Alternative solutions**
Another solution could be to remove the raw data attribute or turn it into a loading method that goes and looks for the original raw file. This is less desirable since it returns to the problem of locating the raw data that was used to create the structured file.

**Comment by ardunn** [comment]
So after examining this a bit, it seems the breakdown is this:

- Reading the data file into a dictionary: 42% of the time
- Creating the Datapath object (from_dict): 58% of the time

By simply not adding in the raw data, we can reduce the "Creating the Datapath object" by about 78%, AKA reducing the total load time by 31%.

This simple fix _might_ also take care of the memory issues.
