### ISSUE TITLE
Files generated by tests

### ISSUE THREAD

**Issue by tinosulzer** [TRI-AMDD/beep#53]
The following files are generated by running tests:
```
beep/procedure_templates/diagnosticV2.json
beep/procedure_templates/diagnosticV3.json
beep/tests/test_files/test_LA4_waveform.MWF
beep/tests/test_files/test_US06_waveform.MWF
beep/validation_schemas/validation_records.json
```
Should `.json` and `.MWF` be added to `.gitignore`?

**Comment by patrickherring-TRI** [comment]
These are actually files that we generally look at to verify the tests. We can remove those files by running the tests in a scratch directory.

**Comment by tinosulzer** [comment]
Running in a scratch directory sounds good, or just adding those file formats to `.gitignore`. The danger now is that someone might accidentally commit those files and add unnecessary clutter to the git repository (similarly these files could be generated by normal running of BEEP and then accidentally committed).

**Comment by chirranjeevigopal-TRI** [comment]
Fair point, I will add them to .gitignore.

**Comment by chirranjeevigopal-TRI** [comment]
PR in review

**Comment by chirranjeevigopal-TRI** [comment]
@tinosulzer Just merged a PR to fix this issue. Lmk if the issue persists, else I'll close it out.

**Comment by tinosulzer** [comment]
I still got this one: `beep/tests/test_files/test_model.model`

**Comment by chirranjeevigopal-TRI** [comment]
The new commit should fix this.

**Comment by tinosulzer** [comment]
Yes, fixed now, thanks
