### ISSUE TITLE
Calculate Diagnostic Features at Every Diagnostic Cycle

### ISSUE THREAD

**Issue by pasinger** [TRI-AMDD/beep#567]
Currently, diagnostic features are calculated at the first and second diagnostic and the difference between the two is reported. This format is amenable to early prediction, but analysis of the battery health across lifetime would be better served by having the features reported across every cycle.

Some diagnostic information is available in the structured data in the diagnostic_summary field, but what's available there is not comprehensive.

I propose making a distinction between 1) "EarlyFeatures", which are a difference on the first two diagnostics (or between the first and some other diagnostic number specified in the featurizer hyperparameters) and 2) "CycleFeatures", which are the diagnostic features reported across all diagnostic cycles.

**Comment by shijingsun-TRI** [comment]
@ardunn would you help write unit tests for issue please? Thank you!

**Comment by ardunn** [comment]
Sure.

Since this pertains directly to the PR, I'm just going to copy+paste @pasinger 's text there and close this issue, as everything in this issue will be in the PR
