### ISSUE TITLE
[Feature Request] Novonix Datapath

### ISSUE THREAD

**Issue by shijingsun-TRI** [TRI-AMDD/beep#610]
**Is your feature request related to a problem? Please describe.**
We'd like to process cycling data from Novonix via beep, including reading files and structure it.

**Describe the solution you'd like**
beep.structure(Novonix file) returns structured object, datapath.structured_data returns structured files, datapath.structured_summary returns cycle summary stats.

**Additional context**
Please check and add content to PR Novonix_ingestion

**Comment by ardunn** [comment]
related to #611

**Comment by ardunn** [comment]
Closed by #611
